url: "https://hexagone22.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "website" # the subpath of your site, e.g. /blog
environment: production

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

markdown: kramdown


title: "Cuisiniste & Aménagemen intérieur à Domicile Saint-Brieuc, Erquy, Saint-Quay Portrieux" # the name of your site, e.g. ACME Corp.
tagline: "Tagline"
description: "Emmanuelle Helloco se déplace chez vous dans les côtes d'Armor pour vos projets de cuisine et d'aménagement d'intérieur, dressing, living-room, électro-ménager"
# logo: /assets/images/logoLSA.png
locale: "Fr"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# facebook:
#   app_id: 61551899341644

# social:
#   links:
#   - https://www.facebook.com/profile.php?id=61551899341644

