url: "https://www.hexagonecreation.fr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
environment: production

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

markdown: kramdown


title: "Cuisiniste & Aménagement Intérieur à domicile" # the name of your site, e.g. ACME Corp.
description: "Emmanuel Le Helloco se déplace chez vous autour de Saint-Brieuc pour vos projets de cuisine et d'aménagement d'intérieur, salle de bain, dressing, living, électro-ménager"
# tagline: "Tagline"
# logo: /assets/images/logoLSA.png
locale: "Fr"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# facebook:
#   app_id: 61551899341644

# social:
#   links:
#   - https://www.facebook.com/profile.php?id=61551899341644

